# Generated by Django 5.2.5 on 2025-08-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_episode_duration_episode_episode_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name_plural': 'Episodes'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
    ]
