# Generated by Django 5.2.5 on 2025-08-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_alter_episode_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
    ]
